# Ohnologs & eQTLs

### Background

Enrichment for eQTLs of ohnologs and nonohnologs.

### Imports

In [1]:
import pandas as pd
import re
import os.path

### Functions

In [2]:
def removeGeneIDVersions(text):
    return re.findall('(ENSG\d+)', text)[0]

### Input/Output files

---

### eQTL affected tissues per gene
[Back to top](#Outline)

In [3]:
genesTestedForeQTLsWithNumberOfTissues = pd.read_csv('../outputFiles/GTExV7/genesTestedWithNumberOfTissues.csv')
genesTestedForeQTLsWithNumberOfTissues.head()

   expressedTissues  Ensembl Gene ID
0                48  ENSG00000272186
1                48  ENSG00000117748
2                48  ENSG00000130856
3                48  ENSG00000169446
4                48  ENSG00000013573

In [4]:
len(genesTestedForeQTLsWithNumberOfTissues)

38187

In [5]:
genesTestedForeQTLsWithNumberOfMergedTissues = pd.read_csv('../outputFiles/GTExV7/genesTestedWithNumberOfMergedTissues.csv')
genesTestedForeQTLsWithNumberOfMergedTissues.head()

   expressedTissues  Ensembl Gene ID
0                26  ENSG00000170604
1                26  ENSG00000178458
2                26  ENSG00000141425
3                26  ENSG00000117115
4                26  ENSG00000105204

In [6]:
PCGenes = pd.read_csv('../datasets/geneLists/Ensembl/EnsV75ProteinCodingGenes1-Y.txt', sep='\t')
PCGenes.head()

   Ensembl Gene ID Chromosome Name  Gene Start (bp)  Gene End (bp)  Strand
0  ENSG00000215405              15         20737094       20747114      -1
1  ENSG00000268343              15         21004687       21005367       1
2  ENSG00000230031              15         21040701       21071643      -1
3  ENSG00000138593              15         49280673       49338760      -1
4  ENSG00000268531              15         22011370       22012050       1

In [9]:
len(PCGenes)

20314

In [7]:
genesTestedForeQTLsWithNumberOfTissues = pd.merge(genesTestedForeQTLsWithNumberOfTissues, PCGenes, on="Ensembl Gene ID")
genesTestedForeQTLsWithNumberOfMergedTissues = pd.merge(genesTestedForeQTLsWithNumberOfMergedTissues, PCGenes, on="Ensembl Gene ID")

In [8]:
len(genesTestedForeQTLsWithNumberOfTissues)

19067

##### Bonferroni-corrected

In [16]:
genesWitheQTLTissueCountBonferroni = pd.read_csv('../outputFiles/GTExV7/genesWithNumberOfBonferroniAffectedTissues.csv', index_col = 0)
genesWitheQTLTissueCountBonferroni.head()

   Ensembl Gene ID  affectedTissues
0  ENSG00000138593                4
1  ENSG00000166351                1
2  ENSG00000168675                1
3  ENSG00000188992               13
4  ENSG00000185272                8

In [17]:
genesWitheQTLTissueCountBonferroni = pd.merge(genesWitheQTLTissueCountBonferroni, genesTestedForeQTLsWithNumberOfTissues, on='Ensembl Gene ID', how='right')
genesWitheQTLTissueCountBonferroni

,Ensembl Gene ID,affectedTissues,expressedTissues,Chromosome Name,Gene Start (bp),Gene End (bp),Strand
0,ENSG00000138593,4.0,48,15,49280673,49338760,-1
1,ENSG00000166351,1.0,1,21,14982498,15013906,1
2,ENSG00000168675,1.0,47,18,13217497,13652754,1
3,ENSG00000188992,13.0,30,21,15481134,15583166,-1
4,ENSG00000185272,8.0,48,21,15588451,15600693,1
5,ENSG00000182974,1.0,1,15,22368478,22369561,1
6,ENSG00000155304,1.0,48,21,15743436,15755805,-1
7,ENSG00000153575,8.0,48,15,22833395,22873892,1
8,ENSG00000180530,2.0,48,21,16333556,16437321,-1
9,ENSG00000137824,9.0,48,15,41028082,41048049,-1
10,ENSG00000137880,1.0,48,15,41056218,41059906,1
11,ENSG00000104129,9.0,48,15,41060067,41099675,-1
12,ENSG00000177150,4.0,48,18,13663346,13726662,-1
13,ENSG00000155313,1.0,48,21,17102344,17252377,1
14,ENSG00000101638,4.0,48,18,44259081,44339220,-1
15,ENSG00000154639,4.0,45,21,18884700,18965897,1
16,ENSG00000101654,6.0,48,18,13726659,13764557,1
17,ENSG00000078043,8.0,48,18,44388353,44500123,-1
18,ENSG00000156958,3.0,48,15,49447853,49660066,1
19,ENSG00000154640,4.0,48,21,18965971,18985265,-1
20,ENSG00000140416,9.0,48,15,63334831,63364114,1
21,ENSG00000154642,6.0,48,21,19161284,19191703,-1
22,ENSG00000140577,8.0,48,15,91073157,91188577,1
23,ENSG00000166140,36.0,48,15,41099284,41106767,1
24,ENSG00000101138,10.0,48,20,54967427,54979518,1
25,ENSG00000154645,10.0,45,21,19273580,19639690,1
26,ENSG00000068793,15.0,48,15,22892005,23006016,1
27,ENSG00000182931,13.0,22,20,44313292,44333658,-1
28,ENSG00000154646,1.0,2,21,19641433,19858197,-1
29,ENSG00000168634,5.0,11,20,44330655,44337456,1
...,...,...,...,...,...,...,...
19037,ENSG00000172320,NaN,1,11,59210617,59211667,1
19038,ENSG00000171053,NaN,1,11,125616188,125619762,1
19039,ENSG00000178279,NaN,1,16,11361605,11363390,-1
19040,ENSG00000142511,NaN,1,19,51273721,51274989,1
19041,ENSG00000248789,NaN,1,5,51303865,51376821,1
19042,ENSG00000221855,NaN,1,7,143174966,143175889,1
19043,ENSG00000198704,NaN,1,6,28471073,28495992,-1
19044,ENSG00000186103,NaN,1,3,121289551,121305481,1
19045,ENSG00000176893,NaN,1,11,4935900,4936922,-1
19046,ENSG00000196578,NaN,1,3,97806017,97806946,1
19047,ENSG00000163530,NaN,1,3,109012635,109035364,-1
19048,ENSG00000259518,NaN,1,15,82380935,82390035,1
19049,ENSG00000176219,NaN,1,14,20691791,20692964,1
19050,ENSG00000221867,NaN,1,X,151934652,151938240,-1
19051,ENSG00000228607,NaN,1,11,113650469,113651222,1
19052,ENSG00000166152,NaN,1,16,49407734,49433342,1
19053,ENSG00000221910,NaN,1,7,143632259,143633372,1
19054,ENSG00000189326,NaN,1,X,142113704,142122488,1
19055,ENSG00000177596,NaN,1,13,74987094,74993252,-1
19056,ENSG00000258150,NaN,1,16,29476288,29479154,-1
19057,ENSG00000164256,NaN,1,5,23507264,23528706,1
19058,ENSG00000178928,NaN,1,19,48304500,48322308,-1
19059,ENSG00000179755,NaN,1,16,34256507,34257278,1
19060,ENSG00000129965,NaN,1,11,2153768,2182439,-1
19061,ENSG00000169906,NaN,1,X,16668281,16672793,1
19062,ENSG00000186509,NaN,1,11,57791353,57949088,1
19063,ENSG00000236980,NaN,1,3,49215065,49229291,-1
19064,ENSG00000132631,NaN,1,20,18794370,18795033,1
19065,ENSG00000170279,NaN,1,7,148287657,148312952,1
19066,ENSG00000179817,NaN,1,11,18194384,18195827,1

In [18]:
genesWitheQTLTissueCountBonferroni['affectedTissues'].fillna(0, inplace=True)

##### Ohnologs

In [20]:
ohnologsRelaxed = pd.read_csv('../datasets/geneLists/Singh and Isambert/hsapiens.Pairs.Relaxed.2R.Ens75.1-Y.txt')
ohnologsRelaxed.head()

   Ensembl Gene ID
0  ENSG00000164236
1  ENSG00000147465
2  ENSG00000095464
3  ENSG00000078804
4  ENSG00000155744

In [21]:
SSDsRelaxedOhnos = pd.read_csv('../datasets/geneLists/SSDsRelaxedOhnos.txt')
SSDsRelaxedOhnos.head()

   Ensembl Gene ID
0  ENSG00000215405
1  ENSG00000268343
2  ENSG00000230031
3  ENSG00000268531
4  ENSG00000233917

In [22]:
singletons = pd.read_csv('../datasets/geneLists/singletons.txt')
singletons.head()

   Ensembl Gene ID
0  ENSG00000269182
1  ENSG00000155304
2  ENSG00000243440
3  ENSG00000180530
4  ENSG00000259458

In [23]:
genesWitheQTLTissueCountBonferroni.loc[:, 'type'] = ''
genesWitheQTLTissueCountBonferroni.loc[genesWitheQTLTissueCountBonferroni['Ensembl Gene ID'].isin(ohnologsRelaxed['Ensembl Gene ID']) , 'type'] = 'ohno'
genesWitheQTLTissueCountBonferroni.loc[genesWitheQTLTissueCountBonferroni['Ensembl Gene ID'].isin(SSDsRelaxedOhnos['Ensembl Gene ID']) , 'type'] = 'SSD'
genesWitheQTLTissueCountBonferroni.loc[genesWitheQTLTissueCountBonferroni['Ensembl Gene ID'].isin(singletons['Ensembl Gene ID']) , 'type'] = 'singleton'
genesWitheQTLTissueCountBonferroni.groupby('type').describe()

          Gene End (bp)                                                    \
                  count          mean           std      min          25%
type
SSD              6777.0  7.361875e+07  5.627181e+07  70008.0  30894236.00
ohno             6550.0  7.597553e+07  5.583925e+07  31427.0  32878425.75
singleton        5740.0  7.385908e+07  5.555843e+07  69452.0  31880189.75

                                                 Gene Start (bp)  \
                  50%           75%          max           count
type
SSD        56667898.0  1.095848e+08  249214145.0          6777.0
ohno       61947334.0  1.134841e+08  246670614.0          6550.0
singleton  58760361.0  1.104328e+08  249143716.0          5740.0

                         ...  affectedTissues       expressedTissues  \
                   mean  ...              75%   max            count
type                     ...
SSD        7.356490e+07  ...             11.0  48.0           6777.0
ohno       7.587494e+07  ...              9.0  48.0           6550.0
singleton  7.381176e+07  ...             12.0  48.0           5740.0


                mean        std  min   25%   50%   75%   max
type
SSD        39.105947  15.847822  1.0  40.0  48.0  48.0  48.0
ohno       43.522290  10.591560  1.0  46.0  48.0  48.0  48.0
singleton  41.820383  13.721230  1.0  47.0  48.0  48.0  48.0

[3 rows x 40 columns]

In [25]:
genesWitheQTLTissueCountBonferroni.head()

,Ensembl Gene ID,affectedTissues,expressedTissues,Chromosome Name,Gene Start (bp),Gene End (bp),Strand,type
0,ENSG00000138593,4.0,48,15,49280673,49338760,-1,ohno
1,ENSG00000166351,1.0,1,21,14982498,15013906,1,SSD
2,ENSG00000168675,1.0,47,18,13217497,13652754,1,SSD
3,ENSG00000188992,13.0,30,21,15481134,15583166,-1,SSD
4,ENSG00000185272,8.0,48,21,15588451,15600693,1,ohno

In [26]:
genesWitheQTLTissueCountBonferroni['propOfExpressedAffectedByeQTL'] = genesWitheQTLTissueCountBonferroni['affectedTissues'] / genesWitheQTLTissueCountBonferroni['expressedTissues']

In [28]:
genesWitheQTLTissueCountBonferroni.groupby('type').describe()

          Gene End (bp)                                                    \
                  count          mean           std      min          25%
type
SSD              6777.0  7.361875e+07  5.627181e+07  70008.0  30894236.00
ohno             6550.0  7.597553e+07  5.583925e+07  31427.0  32878425.75
singleton        5740.0  7.385908e+07  5.555843e+07  69452.0  31880189.75

                                                 Gene Start (bp)  \
                  50%           75%          max           count
type
SSD        56667898.0  1.095848e+08  249214145.0          6777.0
ohno       61947334.0  1.134841e+08  246670614.0          6550.0
singleton  58760361.0  1.104328e+08  249143716.0          5740.0

                        ...  expressedTissues        \
                   mean ...               75%   max
type                    ...
SSD        7.356490e+07 ...              48.0  48.0
ohno       7.587494e+07 ...              48.0  48.0
singleton  7.381176e+07 ...              48.0  48.0

          propOfExpressedAffectedByeQTL                                     \
                                  count      mean       std  min       25%
type
SSD                              6777.0  0.204547  0.252103  0.0  0.020833
ohno                             6550.0  0.151683  0.177107  0.0  0.030303
singleton                        5740.0  0.200093  0.242668  0.0  0.020833


                50%       75%  max
type
SSD        0.104167  0.291667  1.0
ohno       0.086957  0.208333  1.0
singleton  0.104167  0.291667  1.0

[3 rows x 48 columns]

In [29]:
genesWitheQTLTissueCountBonferroni[genesWitheQTLTissueCountBonferroni['affectedTissues']>0].groupby('type').describe()

          Gene End (bp)                                                    \
                  count          mean           std      min          25%
type
SSD              5473.0  7.391207e+07  5.629434e+07  73545.0  31054296.00
ohno             5604.0  7.573204e+07  5.583758e+07  31427.0  32638860.25
singleton        4661.0  7.372066e+07  5.589631e+07  69452.0  31499709.00

                                                 Gene Start (bp)  \
                  50%           75%          max           count
type
SSD        57233335.0  1.097808e+08  249153343.0          5473.0
ohno       61984211.5  1.133391e+08  246670614.0          5604.0
singleton  58554431.0  1.104216e+08  248903150.0          4661.0

                        ...  expressedTissues        \
                   mean ...               75%   max
type                    ...
SSD        7.385313e+07 ...              48.0  48.0
ohno       7.562491e+07 ...              48.0  48.0
singleton  7.366924e+07 ...              48.0  48.0

          propOfExpressedAffectedByeQTL                                        \
                                  count      mean       std       min     25%
type
SSD                              5473.0  0.253282  0.257596  0.020833  0.0625
ohno                             5604.0  0.177289  0.179228  0.020833  0.0625
singleton                        4661.0  0.246414  0.247197  0.020833  0.0625


                50%       75%  max
type
SSD        0.145833  0.354167  1.0
ohno       0.120000  0.229167  1.0
singleton  0.145833  0.354167  1.0

[3 rows x 48 columns]

In [30]:
genesWitheQTLTissueCountBonferroni.to_csv("../outputFiles/genesWitheQTLTissueCountBonferroniAndOhnologStatus.csv", sep='\t')

##### Metasoft

In [33]:
genesWitheQTLTissueCountMetasoft = pd.read_csv('../outputFiles/GTExV7/genesWithNumberOfMetasoftAffectedTissues.csv', index_col = 0)
genesWitheQTLTissueCountMetasoft = pd.merge(genesWitheQTLTissueCountMetasoft, genesTestedForeQTLsWithNumberOfTissues, on='Ensembl Gene ID', how='right')
genesWitheQTLTissueCountMetasoft['affectedTissues'].fillna(0, inplace=True)
genesWitheQTLTissueCountMetasoft['propOfExpressedAffectedByeQTL'] = genesWitheQTLTissueCountMetasoft['affectedTissues'] / genesWitheQTLTissueCountMetasoft['expressedTissues']
genesWitheQTLTissueCountMetasoft.loc[:, 'type'] = ''
genesWitheQTLTissueCountMetasoft.loc[genesWitheQTLTissueCountMetasoft['Ensembl Gene ID'].isin(ohnologsRelaxed['Ensembl Gene ID']) , 'type'] = 'ohno'
genesWitheQTLTissueCountMetasoft.loc[genesWitheQTLTissueCountMetasoft['Ensembl Gene ID'].isin(SSDsRelaxedOhnos['Ensembl Gene ID']) , 'type'] = 'SSD'
genesWitheQTLTissueCountMetasoft.loc[genesWitheQTLTissueCountMetasoft['Ensembl Gene ID'].isin(singletons['Ensembl Gene ID']) , 'type'] = 'singleton'
genesWitheQTLTissueCountMetasoft

,Ensembl Gene ID,affectedTissues,expressedTissues,Chromosome Name,Gene Start (bp),Gene End (bp),Strand,propOfExpressedAffectedByeQTL,type
0,ENSG00000138593,24.0,48,15,49280673,49338760,-1,0.500000,ohno
1,ENSG00000166157,1.0,3,21,10906201,11029719,-1,0.333333,SSD
2,ENSG00000168675,10.0,47,18,13217497,13652754,1,0.212766,SSD
3,ENSG00000188992,30.0,30,21,15481134,15583166,-1,1.000000,SSD
4,ENSG00000185272,48.0,48,21,15588451,15600693,1,1.000000,ohno
5,ENSG00000155304,23.0,48,21,15743436,15755805,-1,0.479167,singleton
6,ENSG00000197414,1.0,4,15,22736246,22746002,1,0.250000,SSD
7,ENSG00000166200,44.0,48,15,49398268,49447858,-1,0.916667,SSD
8,ENSG00000155307,4.0,48,21,15857549,15955723,-1,0.083333,SSD
9,ENSG00000243440,2.0,7,21,15964251,16031142,-1,0.285714,singleton
10,ENSG00000153575,48.0,48,15,22833395,22873892,1,1.000000,SSD
11,ENSG00000180530,12.0,48,21,16333556,16437321,-1,0.250000,singleton
12,ENSG00000137824,47.0,48,15,41028082,41048049,-1,0.979167,ohno
13,ENSG00000259458,1.0,4,15,62929371,62937490,-1,0.250000,singleton
14,ENSG00000137880,3.0,48,15,41056218,41059906,1,0.062500,singleton
15,ENSG00000104129,48.0,48,15,41060067,41099675,-1,1.000000,SSD
16,ENSG00000177150,43.0,48,18,13663346,13726662,-1,0.895833,SSD
17,ENSG00000155313,9.0,48,21,17102344,17252377,1,0.187500,ohno
18,ENSG00000101638,40.0,48,18,44259081,44339220,-1,0.833333,SSD
19,ENSG00000154639,18.0,45,21,18884700,18965897,1,0.400000,SSD
20,ENSG00000101654,47.0,48,18,13726659,13764557,1,0.979167,singleton
21,ENSG00000078043,47.0,48,18,44388353,44500123,-1,0.979167,ohno
22,ENSG00000156958,42.0,48,15,49447853,49660066,1,0.875000,SSD
23,ENSG00000154640,12.0,48,21,18965971,18985265,-1,0.250000,SSD
24,ENSG00000140416,40.0,48,15,63334831,63364114,1,0.833333,ohno
25,ENSG00000154642,20.0,48,21,19161284,19191703,-1,0.416667,singleton
26,ENSG00000140577,47.0,48,15,91073157,91188577,1,0.979167,ohno
27,ENSG00000166140,48.0,48,15,41099284,41106767,1,1.000000,singleton
28,ENSG00000101138,48.0,48,20,54967427,54979518,1,1.000000,SSD
29,ENSG00000154645,34.0,45,21,19273580,19639690,1,0.755556,SSD
...,...,...,...,...,...,...,...,...,...
19037,ENSG00000186103,0.0,1,3,121289551,121305481,1,0.000000,singleton
19038,ENSG00000176893,0.0,1,11,4935900,4936922,-1,0.000000,SSD
19039,ENSG00000196578,0.0,1,3,97806017,97806946,1,0.000000,SSD
19040,ENSG00000163530,0.0,1,3,109012635,109035364,-1,0.000000,SSD
19041,ENSG00000259518,0.0,1,15,82380935,82390035,1,0.000000,singleton
19042,ENSG00000176219,0.0,1,14,20691791,20692964,1,0.000000,SSD
19043,ENSG00000221867,0.0,1,X,151934652,151938240,-1,0.000000,SSD
19044,ENSG00000228607,0.0,1,11,113650469,113651222,1,0.000000,ohno
19045,ENSG00000166152,0.0,1,16,49407734,49433342,1,0.000000,singleton
19046,ENSG00000221910,0.0,1,7,143632259,143633372,1,0.000000,SSD
19047,ENSG00000131068,0.0,1,20,29956421,29961726,1,0.000000,singleton
19048,ENSG00000189326,0.0,1,X,142113704,142122488,1,0.000000,SSD
19049,ENSG00000177596,0.0,1,13,74987094,74993252,-1,0.000000,singleton
19050,ENSG00000258150,0.0,1,16,29476288,29479154,-1,0.000000,SSD
19051,ENSG00000233701,0.0,1,3,138760944,138763734,-1,0.000000,SSD
19052,ENSG00000164256,0.0,1,5,23507264,23528706,1,0.000000,SSD
19053,ENSG00000178928,0.0,1,19,48304500,48322308,-1,0.000000,SSD
19054,ENSG00000046774,0.0,1,X,141290131,141293076,-1,0.000000,SSD
19055,ENSG00000179755,0.0,1,16,34256507,34257278,1,0.000000,singleton
19056,ENSG00000204849,0.0,1,9,39355699,39361956,1,0.000000,SSD
19057,ENSG00000180658,0.0,1,6,132021520,132022635,-1,0.000000,SSD
19058,ENSG00000180259,0.0,1,20,4711928,4721314,-1,0.000000,singleton
19059,ENSG00000129965,0.0,1,11,2153768,2182439,-1,0.000000,SSD
19060,ENSG00000169906,0.0,1,X,16668281,16672793,1,0.000000,singleton
19061,ENSG00000179407,0.0,1,3,128181282,128186091,-1,0.000000,SSD
19062,ENSG00000186509,0.0,1,11,57791353,57949088,1,0.000000,SSD
19063,ENSG00000236980,0.0,1,3,49215065,49229291,-1,0.000000,singleton
19064,ENSG00000132631,0.0,1,20,18794370,18795033,1,0.000000,SSD
19065,ENSG00000170279,0.0,1,7,148287657,148312952,1,0.000000,singleton
19066,ENSG00000179817,0.0,1,11,18194384,18195827,1,0.000000,SSD

In [34]:
genesWitheQTLTissueCountMetasoft.groupby('type').describe()

          Gene End (bp)                                                    \
                  count          mean           std      min          25%
type
SSD              6777.0  7.361875e+07  5.627181e+07  70008.0  30894236.00
ohno             6550.0  7.597553e+07  5.583925e+07  31427.0  32878425.75
singleton        5740.0  7.385908e+07  5.555843e+07  69452.0  31880189.75

                                                 Gene Start (bp)  \
                  50%           75%          max           count
type
SSD        56667898.0  1.095848e+08  249214145.0          6777.0
ohno       61947334.0  1.134841e+08  246670614.0          6550.0
singleton  58760361.0  1.104328e+08  249143716.0          5740.0

                        ...  expressedTissues        \
                   mean ...               75%   max
type                    ...
SSD        7.356490e+07 ...              48.0  48.0
ohno       7.587494e+07 ...              48.0  48.0
singleton  7.381176e+07 ...              48.0  48.0

          propOfExpressedAffectedByeQTL                                     \
                                  count      mean       std  min       25%
type
SSD                              6777.0  0.646260  0.373773  0.0  0.296296
ohno                             6550.0  0.627873  0.342538  0.0  0.312500
singleton                        5740.0  0.683658  0.367859  0.0  0.354167


                50%       75%  max
type
SSD        0.812500  1.000000  1.0
ohno       0.708333  0.976744  1.0
singleton  0.888889  1.000000  1.0

[3 rows x 48 columns]

In [35]:
genesWitheQTLTissueCountMetasoft[genesWitheQTLTissueCountMetasoft['affectedTissues']>0].groupby('type').describe()

          Gene End (bp)                                                   \
                  count          mean           std      min         25%
type
SSD              6161.0  7.376225e+07  5.596415e+07  73545.0  31236510.0
ohno             6351.0  7.589964e+07  5.584168e+07  31427.0  32809518.5
singleton        5355.0  7.379700e+07  5.573517e+07  69452.0  31744889.0

                                                Gene Start (bp)                \
                  50%          75%          max           count          mean
type
SSD        57233335.0  108960832.0  249214145.0          6161.0  7.370443e+07
ohno       61966203.0  113297392.5  246670614.0          6351.0  7.579709e+07
singleton  58523735.0  110232462.0  249143716.0          5355.0  7.374805e+07

          ...  expressedTissues       propOfExpressedAffectedByeQTL            \
          ...               75%   max                         count      mean
type      ...
SSD       ...              48.0  48.0                        6161.0  0.710876
ohno      ...              48.0  48.0                        6351.0  0.647547
singleton ...              48.0  48.0                        5355.0  0.732810


                std       min       25%       50%       75%  max
type
SSD        0.328232  0.020833  0.437500  0.875000  1.000000  1.0
ohno       0.329040  0.020833  0.354167  0.729167  0.978723  1.0
singleton  0.330189  0.020833  0.500000  0.916667  1.000000  1.0

[3 rows x 48 columns]

In [36]:
genesWitheQTLTissueCountMetasoft.to_csv("../outputFiles/genesWitheQTLTissueCountMetasoftAndOhnologStatus.csv", sep='\t')